server:
  port: 4440
spring:
  application:
    name: sire-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/th3v3rb/sire-config-data
          username: repo.username
          password: repo.key
          default-label: master
          clone-on-start: true
  security:
    user:
      name: app.security.username
      password: app.security.password
  output:
    ansi:
      enabled: always
